- olwebsite-app/package-lock.json
- olwebsite-app/package.json
- olwebsite-app/src/components/App.js
- olwebsite-app/src/components/CarouselWrapper.js
- olwebsite-app/src/components/Header.js
- olwebsite-app/src/styles/App.css
- olwebsite-app/src/styles/carousel-wrapper.css
- olwebsite-app/src/styles/header.css
Added carousel that displays static images on an interval of 6 seconds. Can look into a different carousel if we don't want images displayed but I think we could make the images and display them from the backend down the road, images link to featured content when clicked
> Add feature container on home page

- olwebsite-app/src/pages/LandingView.js
- olwebsite-app/src/style-sheets/components/_carousel-wrapper.scss
- olwebsite-app/src/style-sheets/layout/_app.scss
- olwebsite-app/src/style-sheets/pages/_landing-view.scss
Just cleaned up basic css properties
> Improve Landing view body css

- olwebsite-app/src/components/Footer.js
- olwebsite-app/src/components/Toolbar.js
- olwebsite-app/src/style-sheets/layout/_footer.scss
- olwebsite-app/src/style-sheets/layout/_toolbar.scss
Created footer following mock up, tried to make responsive to scaling but I think that should be fully completed after mockups, in a different scope
> Add Navigation Framework to footer

- olwebsite-app/src/pages/LandingView.js
- olwebsite-app/src/style-sheets/pages/_landing-view.scss
> Feature/add discord and GitHub links on landing view

- olwebsite-app/src/OlWebsiteApp.jsx
- olwebsite-app/src/components/Objects/Input/Input.jsx
- olwebsite-app/src/components/Toolbar.jsx
- olwebsite-app/src/components/Toolbar/Toolbar.jsx
- olwebsite-app/src/components/Toolbar/__tests__/HamburgerToolbar.test.jsx
- olwebsite-app/src/pages/RegisterView.jsx
- olwebsite-app/src/style-sheets/generic/_authentication-input.scss
- olwebsite-app/src/style-sheets/layout/_toolbar.scss
- olwebsite-app/src/style-sheets/main.scss
- olwebsite-app/src/style-sheets/pages/_posts-view.scss
- olwebsite-app/src/style-sheets/pages/_register-view.scss
> Add Register Page

- olwebsite-app/src/style-sheets/layout/_app.scss
- olwebsite-app/src/style-sheets/layout/_toolbar.scss
- olwebsite-app/src/style-sheets/pages/_posts-view.scss
> Make toolbar sticky

- olwebsite-app/src/style-sheets/components/_carousel.scss
- olwebsite-app/src/style-sheets/index.scss
- olwebsite-app/src/style-sheets/layout/_footer.scss
- olwebsite-app/src/style-sheets/layout/_hamburger-toolbar.scss
- olwebsite-app/src/style-sheets/layout/_toolbar.scss
- olwebsite-app/src/style-sheets/main.scss
- olwebsite-app/src/style-sheets/modules/_colors.scss
- olwebsite-app/src/style-sheets/pages/_authentication-view.scss
Just added a color style sheet to store color variables for the project.
> Add color style sheet and use the variables

- olwebsite-app/src/style-sheets/components/_carousel.scss
- olwebsite-app/src/style-sheets/index.scss
- olwebsite-app/src/style-sheets/layout/_footer.scss
- olwebsite-app/src/style-sheets/layout/_hamburger-toolbar.scss
- olwebsite-app/src/style-sheets/layout/_toolbar.scss
- olwebsite-app/src/style-sheets/main.scss
- olwebsite-app/src/style-sheets/modules/_colors.scss
- olwebsite-app/src/style-sheets/pages/_authentication-view.scss
Provides a place where color variables will be stored so that they can be used consistently across the rest of the site.
- Also implement in a few places.
- Organize and annotate a few things
> Add color style sheet

- olwebsite-app/src/components/Carousel/Carousel.jsx
- olwebsite-app/src/components/Carousel/__tests__/Carousel.test.js
- olwebsite-app/src/components/DotIndicator/DotIndicator.jsx
- olwebsite-app/src/components/DotIndicator/__tests__/DotIndicator.test.js
Added a few tests. If anyone knows how to parameterize tests in Jest, please let me know!
> Add carousel tests

- src/components/Toolbar/Toolbar.jsx
- src/components/Toolbar/__tests__/Toolbar.test.jsx
- src/contexts/UserContext.jsx
- View profile link when the user is logged in
- Fix error with saving user to the local storage
> #31: add conditional view profile page to the header

- src/components/Carousel/__tests__/Carousel.test.js
- src/contexts/UserContext.jsx
- src/pages/LoginView.jsx
- src/pages/RegisterView.jsx
- src/pages/__tests__/RegisterView.test.jsx
rather then showing validation messages on submit, shows messages as users type info
> Handle validation of Authentication Inputs on change

- src/components/Objects/ProtectedRoute/ProtectedRoute.jsx
- src/components/Objects/ProtectedRoute/__tests__/ProtectedRoute.test.js
- src/components/Toolbar/Toolbar.jsx
- src/contexts/UserContext.jsx
- src/pages/LoginView.jsx
- src/pages/RegisterView.jsx
- src/pages/__tests__/RegisterView.test.jsx
Redirect unauthenticated user to login page and redirect to homepage or referrer.
> #90 Successful Authentication Redirect

- src/OlWebsiteApp.jsx
- src/pages/index.js
Refactored page imports into one file. Closes #105
> Improve view imports

- src/assets/SocialMediaIcons/SocialMediaIcons.jsx
- src/components/Footer/js/footerLinks.js
- src/constants/social-media-constants.js
- src/pages/LandingView.jsx
> discord links

- src/pages/PageNotFoundView.jsx
- src/style-sheets/generic/_button.scss
- src/style-sheets/pages/_page-not-found-view.scss
> Refactor buttons wrapped in links

- src/OlWebsiteApp.jsx
- src/components/Footer/js/footerLinks.js
- src/components/Toolbar/Toolbar.jsx
Changed the NavLink/Route path params so that they are less verbose.
/contact
/projects
/team 
/about
> Shorten url postfix links

- public/index.html
Not able to test till it's merged sadly lol but this is the meta tags that show up when the link is shared on social media and certain apps (like discord)
> Create link preview for oneleif website

- package-lock.json
- package.json
- src/components/LandingTypingEffect/LandingTypingEffect.jsx
- src/pages/LandingView.jsx
- src/style-sheets/modules/_colors.scss
- src/style-sheets/pages/_landing-view.scss
The section background style needs to be finalized.
> WIP for landing page typing effect section

- src/style-sheets/components/_nav-link-list.scss
- src/style-sheets/generic/_button.scss
- src/style-sheets/generic/_feature-link.scss
- src/style-sheets/layout/_footer.scss
- src/style-sheets/layout/_toolbar.scss
- src/style-sheets/modules/_colors.scss
Hover and active styling for button primary,  navbar links, and footer links.
> Added pseudo selectors with properties that match those on Figma

- src/components/Objects/Button/__tests__/Button.test.js
- src/pages/ContactUsView.jsx
- src/pages/__tests__/ContactUsView.test.js
This gets rid of the disable send button and shows error message if there are any empty inputs when clicked
> Refactor Handling of Button for Contact Us View

- package-lock.json
- package.json
- src/components/TypingEffectWrapper/TypingEffectWrapper.jsx
- src/components/TypingEffectWrapper/__tests__/TypingEffectWrapper.test.js
- src/pages/LandingView.jsx
- src/style-sheets/modules/_colors.scss
- src/style-sheets/pages/_landing-view.scss
I made the TypingEffect more generic and added a test for it.
Originally removed when reverting after code break
> Feature/Typing Effect Added in Landing View

- README.md
LMK if there's any links i didn't list
> Add important links to read me

- package-lock.json
- package.json
- src/App.test.js
- src/OlWebsiteApp.jsx
- src/__tests__/OlWebsiteApp.test.js
- src/components/Footer/NavLinkList.jsx
- src/components/Footer/__tests__/NavLinkList.test.js
- src/components/Objects/Button/Button.jsx
- src/components/Objects/Button/__tests__/Button.test.js
- src/components/Objects/ButtonLink/ButtonLink.jsx
- src/components/Objects/ButtonLink/__tests__/ButtonLink.test.js
- src/components/Objects/FeatureLink/FeatureLink.jsx
- src/components/Objects/FeatureLink/__tests__/FeatureLink.test.js
- src/components/Objects/Icon/Icon.jsx
- src/components/Objects/Icon/__tests__/Icon.test.js
- src/components/Routes/Routes.jsx
- src/components/Toolbar/Toolbar.jsx
- src/components/Toolbar/__tests__/Toolbar.test.jsx
- src/pages/ContactUsView.jsx
- src/pages/LandingView.jsx
- src/pages/PageNotFoundView.jsx
- src/pages/__tests__/ContactUsView.test.js
- src/setupTests.js
- src/style-sheets/generic/_button.scss
- src/style-sheets/pages/_page-not-found-view.scss
Let me know if you want me to capture any specific events. 
Right now we are capturing any clicks related to Buttons/Links/Icons and page history.
> Feature/Implement Google Analytics

- .circleci/config.yml
- package-lock.json
Seems like running test on newer node image helps. When it's merged I'll check if deployment of `master` branch works fine.
> Fix running tests on CircleCI

- src/pages/ContactUsView.jsx
> Updated contact phone number
